# Generated by Django 4.1 on 2022-09-02 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_remove_order_order_user_alter_product_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(upload_to='product_image'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='member_photo',
            field=models.ImageField(upload_to='member_photo'),
        ),
    ]
